Code Forces 136A
izaLukawska/CodeForces pull request #10
Opened 2024-07-01 16:47 UTC by izaLukawska

2024-07-04 16:28 UTC, Wlodek-YouCanDev requested changes

2024-07-04 16:28 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_136A.java
> +        List<String> giftGiven = Arrays.stream(gaveGiftTo.split(" ")).toList();
Why do you need list here if you can use array or even forEach stream method?

2024-07-06 15:09 UTC, izaLukawska commented on src/CodeForces/CodeForces_136A.java
> +        List<String> giftGiven = Arrays.stream(gaveGiftTo.split(" ")).toList();
I need to determine the index of the number of friend who gave the gift to

2024-07-09 13:42 UTC, Wlodek-YouCanDev requested changes

2024-07-09 13:42 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_136A.java
> +        List<String> giftGiven = Arrays.stream(gaveGiftTo.split(" ")).toList();
Ok, but why do you use String type here if index is Integer. Also I do not see possibility to test that resolution with different inputs

2024-07-09 22:54 UTC, Wlodek-YouCanDev approved these changes

2024-07-15 17:23 UTC, merged