Code forces 266 b
izaLukawska/CodeForces pull request #19
Opened 2024-07-22 05:39 UTC by izaLukawska

2024-07-22 16:58 UTC, Wlodek-YouCanDev requested changes

2024-07-22 16:58 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_266B.java
> +        } else {
Why we need else block here if we throws exceptions?

2024-07-22 16:58 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_266B.java
> +public class CodeForces_266B {
There is no possibility to run this code and to check that it works correctly

2024-07-22 16:58 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_266B.java
> +            LinkedList<String> list = Arrays.stream(sex.split("")).collect(Collectors.toCollection(LinkedList::new));
Why here is a LinkedList type? Maybe it is better to use List type to make it convertable?

2024-07-22 16:58 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_266B.java
> +                    if (((String)list.get(i)).equals("G") && ((String)list.get(i - 1)).equals("B")) {
Why you convert object from list to String? Do we need (String) here?

2024-08-12 16:28 UTC, izaLukawska commented
ready for review

2024-08-19 18:49 UTC, Wlodek-YouCanDev approved these changes

2024-08-20 14:13 UTC, merged