Code Forces 677A
izaLukawska/CodeForces pull request #22
Opened 2024-07-22 05:41 UTC by izaLukawska

2024-07-22 17:07 UTC, Wlodek-YouCanDev requested changes

2024-07-22 17:07 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_677A.java
> +    public static int roadWidth(int numberOfFriends, int fenceHeight) {
Solution is nice, but I do not have possibility to test it

2024-08-12 16:31 UTC, izaLukawska commented
ready for review

2024-08-19 18:56 UTC, Wlodek-YouCanDev approved these changes

2024-08-20 14:13 UTC, merged