Code Forces 236A
izaLukawska/CodeForces pull request #4
Opened 2024-06-29 15:07 UTC by izaLukawska

2024-06-30 13:15 UTC, Wlodek-YouCanDev requested changes

2024-06-30 13:15 UTC, Wlodek-YouCanDev commented on src/CodeForces/CodeForces_236A.java
> +        for (int i = 0; i < username.length(); i++) {
It is possible solution, but it is better to use method toCharArray() and use lets say List contructor in HashSet constructor

2024-07-01 15:02 UTC, izaLukawska commented on src/CodeForces/CodeForces_236A.java
> +        for (int i = 0; i < username.length(); i++) {
Do you mean to use stream on this array and create a list and than use it in hashSet?

2024-07-04 16:20 UTC, Wlodek-YouCanDev approved these changes

2024-07-06 15:33 UTC, merged